name: smartsaverwallet
description: A professional expense tracker and savings app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.10.0
  icons_plus: ^5.0.0

  # Animations
  lottie: ^3.3.2
  rive: ^0.13.0
  flutter_animate: ^4.5.0

  # Firebase
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  firebase_analytics: ^12.0.2

  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Navigation
  go_router: ^16.2.4

  # State Management
  provider: ^6.1.5+1

  # Charts & Graphs
  fl_chart: ^1.1.1
  syncfusion_flutter_charts: ^31.1.23

  # Utils
  intl: ^0.20.2
  crypto: ^3.0.3
  uuid: ^4.2.1

  # Image & Media
  image_picker: ^1.0.6
  cached_network_image: ^3.3.1
  percent_indicator: ^4.2.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  shimmer: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo/
    - assets/images/icons/
    - assets/images/illustrations/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
